# Gold Preview

This notebook previews the governance and storytelling Parquet outputs written to the Gold layer.

In [1]:
from pathlib import Path
import pandas as pd

gold_dir = Path('../datalake_gold')
governance_files = sorted(gold_dir.glob('governance_*.parquet'))
storytelling_files = sorted(gold_dir.glob('storytelling_*.parquet'))
gov = pd.read_parquet(governance_files[-1]) if governance_files else pd.DataFrame()
story = pd.read_parquet(storytelling_files[-1]) if storytelling_files else pd.DataFrame()
gov.head(), story.head()

(   snapshot_date  total_tweets  duplicate_rows  duplicate_rate_pct  \
 0  1779978537776            60               0                 0.0

    unique_langs top_lang  null_rate_text  null_rate_createdAt  null_rate_lang  \
 0             3       en             0.0                  0.0             0.0

    null_rate_author_userName  avg_retweetCount  max_retweetCount  \
 0                        0.0              2.72                53

    avg_replyCount  max_replyCount  avg_likeCount  max_likeCount  \
 0            5.08             132          94.27           2013

    avg_quoteCount  max_quoteCount  avg_viewCount  max_viewCount
 0            0.28              11         6704.9         152549  ,
                     id                                               text  \
 0  2060004476669374743  @Bose 1/ Really disappointed with Bose ending ...
 1  2059950505447584179  I got into a screaming match on the bus this m...
 2  2059950392176234910  I got into a screaming match on the bus this m...
 3  2059937735977398654  Ever forget you’re wearing earbuds until the b...
 4  2059914754030776460  Dashy talks about Mercules' camera falling on ...

                         createdAt lang  snapshot_date  retweetCount  \
 0  Thu May 28 14:25:14 +0000 2026   en  1779978537776             0
 1  Thu May 28 10:50:47 +0000 2026   en  1779978537776             0
 2  Thu May 28 10:50:20 +0000 2026   en  1779978537776             0
 3  Thu May 28 10:00:02 +0000 2026   en  1779978537776             0
 4  Thu May 28 08:28:43 +0000 2026   en  1779978537776             4

    replyCount  likeCount  quoteCount  viewCount  isReply author_userName  \
 0           1          0           0          2    False  SouthernFreeez
 1           0          1           0         27    False  oluwafemi10591
 2           0          1           0         17    False  oluwafemi10591
 3           0          0           0         11    False      GearReview
 4           0        391           0      37439    False        CDLHater

             author_name  author_followers  author_isVerified  \
 0         Cyprus Gunner               315              False
 1               Phemmie              4126              False
 2               Phemmie              4126              False
 3  ActiveGearReview.com              4058              False
 4     CDL Hater Central             26352              False

    author_isBlueVerified      author_location  engagement_total  text_length
 0                  False               London                 3          274
 1                   True               Lagos                 28         1070
 2                   True               Lagos                 18         1070
 3                  False  Twin Lake, Michigan                11          166
 4                   True  Call of Duty League             37834          301  )

In [2]:
if not gov.empty:
    display(gov)
else:
    print('No governance Parquet files found.')

if not story.empty:
    display(story)
else:
    print('No storytelling Parquet files found.')

,snapshot_date,total_tweets,duplicate_rows,duplicate_rate_pct,unique_langs,top_lang,null_rate_text,null_rate_createdAt,null_rate_lang,null_rate_author_userName,avg_retweetCount,max_retweetCount,avg_replyCount,max_replyCount,avg_likeCount,max_likeCount,avg_quoteCount,max_quoteCount,avg_viewCount,max_viewCount
0,1779978537776,60,0,0.0,3,en,0.0,0.0,0.0,0.0,2.72,53,5.08,132,94.27,2013,0.28,11,6704.9,152549

,id,text,createdAt,lang,snapshot_date,retweetCount,replyCount,likeCount,quoteCount,viewCount,isReply,author_userName,author_name,author_followers,author_isVerified,author_isBlueVerified,author_location,engagement_total,text_length
0,2060004476669374743,@Bose 1/ Really disappointed with Bose ending ...,Thu May 28 14:25:14 +0000 2026,en,1779978537776,0,1,0,0,2,False,SouthernFreeez,Cyprus Gunner,315,False,False,London,3,274
1,2059950505447584179,I got into a screaming match on the bus this m...,Thu May 28 10:50:47 +0000 2026,en,1779978537776,0,0,1,0,27,False,oluwafemi10591,Phemmie,4126,False,True,Lagos,28,1070
2,2059950392176234910,I got into a screaming match on the bus this m...,Thu May 28 10:50:20 +0000 2026,en,1779978537776,0,0,1,0,17,False,oluwafemi10591,Phemmie,4126,False,True,Lagos,18,1070
3,2059937735977398654,Ever forget you’re wearing earbuds until the b...,Thu May 28 10:00:02 +0000 2026,en,1779978537776,0,0,0,0,11,False,GearReview,ActiveGearReview.com,4058,False,False,"Twin Lake, Michigan",11,166
4,2059914754030776460,Dashy talks about Mercules' camera falling on ...,Thu May 28 08:28:43 +0000 2026,en,1779978537776,4,0,391,0,37439,False,CDLHater,CDL Hater Central,26352,False,True,Call of Duty League,37834,301
5,2059899870865932490,this was my favorite solo i used to play it ev...,Thu May 28 07:29:34 +0000 2026,en,1779978537776,0,1,0,0,120,False,6060_0606,socrates,114,False,False,02 casual fan,121,98
6,2059872425068704029,when I left japan the last time I bought bluet...,Thu May 28 05:40:31 +0000 2026,en,1779978537776,0,0,15,0,356,False,merrygomaru,キラ👾₊˚⊹★,4526,False,False,🐈‍⬛🎸 日本語/ENG OK,371,200
7,2059782299370070471,Completed my mini home theater set up thingy f...,Wed May 27 23:42:23 +0000 2026,en,1779978537776,0,0,0,0,21,False,tytiethai_,Antygravity,89,False,False,,21,257
8,2059696184248401937,When my Garmin watch falls off at night and ha...,Wed May 27 18:00:12 +0000 2026,en,1779978537776,0,0,2,0,148,False,saffronandsky,a tired human,2525,False,True,"Pacific NW, USA",150,175
9,2059641565706871191,Big buyer's remorse on the the choice of color...,Wed May 27 14:23:10 +0000 2026,en,1779978537776,0,0,0,0,44,False,My_Capering_Id,Iddy,787,False,True,Under Your Skin,44,248
10,2059597381109440747,I just watched a stereo test video on YouTube ...,Wed May 27 11:27:35 +0000 2026,en,1779978537776,0,0,0,0,10,False,sixsevenahhblud,lvl 1 crook,17,False,False,ла-манш,10,136
11,2059467952928559187,I got fed up with streaming and got a mp3 play...,Wed May 27 02:53:17 +0000 2026,en,1779978537776,0,1,0,0,21,False,RRobovski,Robert Turner,341,False,True,"Long Beach, CA",22,189
12,2059422706005614858,I got a new 🐇🕳️ for @Chrissssjohnson ….emf! is...,Tue May 26 23:53:29 +0000 2026,en,1779978537776,0,0,0,0,20,False,clueless_trade,clueless_trader,40,False,False,,20,85
13,2059421694306206106,I've been using earbuds for streaming the past...,Tue May 26 23:49:28 +0000 2026,en,1779978537776,2,3,16,0,343,False,Zeke_The_Human,Zeke the Human |🇦🇺🛸| Vtuber,3298,False,False,Australia,364,279
14,2059338698131419241,i was tryna get my headphone jack into my moni...,Tue May 26 18:19:40 +0000 2026,en,1779978537776,0,0,2,0,71,False,WizzyLizzy06,WizzyLizzy,151,False,False,United Kingdom,73,145
15,2059334459598499931,Quick test of my new Tufteln audio breakout bo...,Tue May 26 18:02:50 +0000 2026,en,1779978537776,1,1,16,0,583,False,commsonawire,TangoOscarMike-N3WS,578,False,True,South West PA,601,237
16,2059265460542095608,I've been using the FitBit Air for about a wee...,Tue May 26 13:28:39 +0000 2026,en,1779978537776,15,38,1310,0,152549,False,DurvidImel,David ImeI,76329,False,True,Somewhere,153912,277
17,2059250440798146655,Does anyone have a smart watch with great batt...,Tue May 26 12:28:58 +0000 2026,en,1779978537776,0,2,1,0,392,False,AllAcesCards,All Aces Cards,1961,False,True,"Atlanta, GA",395,251
18,2059217412202057937,i bought regular sony shmegular earbuds (not i...,Tue May 26 10:17:44 +0000 2026,en,1779978537776,0,0,0,0,62,False,maihimebow,mai,588,False,False,,62,161
19,2059206596811776120,Heartbreaking: audio from the earphones i got ...,Tue May 26 09:34:45 +0000 2026,en,1779978537776,0,0,0,0,14,False,hegaumai,¯﹃¯,41,False,False,ゴミ垢だけです,14,133
20,2059901653986181162,BS. My 22yr old MacBook starts and runs like o...,Thu May 28 07:36:40 +0000 2026,en,1779978537776,0,0,0,0,27,False,craniosurgeon,Christian Duncan,32,False,False,"Liverpool, England",27,245
21,2059864746392781018,Crazy to think that I've had my macbook pro fo...,Thu May 28 05:10:00 +0000 2026,en,1779978537776,0,1,0,0,49,False,wisedawn13,Asher 🖤 || new fic,2733,False,False,Canada 🇨🇦,50,277
22,2059819697735094584,The PELADN WO4 AMD Ryzen 5 Mini PC is an amaz...,Thu May 28 02:11:00 +0000 2026,en,1779978537776,0,0,0,0,25,False,DaveTaylor,Dave Taylor,13277,False,True,"Boulder, CO",25,299
23,2059808927743893993,You may think that I bought my MacBook Pro bec...,Thu May 28 01:28:12 +0000 2026,en,1779978537776,39,41,2013,2,49000,False,SnazzyLabs,Quinn Nelson,295464,False,True,"Salt Lake City, Utah",51095,271
24,2059760658950861291,Why don’t we talk about how many times Microso...,Wed May 27 22:16:24 +0000 2026,en,1779978537776,0,0,0,0,36,False,8kPegasus,CMA 8K DUALSENSIBLE,1001,False,True,England,36,261
25,2059750854589026479,I think I got 6p into this at like half screen...,Wed May 27 21:37:26 +0000 2026,en,1779978537776,0,0,0,0,18,False,Noah_C_Moore,TheMessiuh,471,False,False,,18,113
26,2059714859189600748,i bought a dell keyboard and it's the smoothes...,Wed May 27 19:14:24 +0000 2026,en,1779978537776,0,1,1,0,15,False,minallkamel,mina,147,False,True,,17,114
27,2059661083883753815,Pretty happy with my YTD performance: +17% whi...,Wed May 27 15:40:43 +0000 2026,en,1779978537776,1,2,8,1,668,False,Samurai__Stock,samurai,1442,False,True,,680,305
28,2059559483462816010,Audi B9 S5 launched in 2017 on the MLB Evo pla...,Wed May 27 08:57:00 +0000 2026,en,1779978537776,4,1,26,0,1615,False,Autoweltmedia,Autowelt,7896,False,True,,1646,554
29,2059260000581681547,@HP wanted to say I bought my first gaming pc ...,Tue May 26 13:06:57 +0000 2026,en,1779978537776,0,1,1,0,42,False,GHSTCraft420,⛧🖤GHSTCraft🖤⛧,105,False,False,mothers dwelling/red forest,44,146
30,2058870136543617235,My #Hermes agents run on a scrap macbook ait w...,Mon May 25 11:17:47 +0000 2026,en,1779978537776,0,0,0,0,25,False,ViberPsychosis,Vibe Scribe,15,False,True,404 Land,25,252
31,2058746234400076009,?iQ1 Secret ?iQ1 How my intel know they Turn o...,Mon May 25 03:05:26 +0000 2026,en,1779978537776,0,0,0,0,258,False,Ark13Vongdara,Zack Vongdara,302,False,False,,258,304
32,2058743641645150533,I have seen the future with far less impressiv...,Mon May 25 02:55:08 +0000 2026,en,1779978537776,0,0,1,0,131,False,timhnln,Tim Hanlon,1251,False,True,Melbourne,132,211
33,2058722411030196719,A couple years ago I got really high and watch...,Mon May 25 01:30:46 +0000 2026,en,1779978537776,0,1,1,0,46,False,CassieKatarn,Cassie Katarn,432,False,False,a drafty apartment,48,256
34,2058603864220139575,10 years ago I bought Overwatch (instead of Ba...,Sun May 24 17:39:42 +0000 2026,en,1779978537776,0,2,20,0,269,False,RaineOW_,XZL | Raine 🌱,483,False,False,Nova Scotia,291,279
35,2058554894424891801,Would love some performance optimization for @...,Sun May 24 14:25:07 +0000 2026,en,1779978537776,0,0,0,0,28,False,only1rawr,rawR🦖🤯🫩,100,False,True,Hidden Leaf Village,28,403
36,2058467915050148101,@RelianceDigital @Lenovo_in \nI am extremely u...,Sun May 24 08:39:30 +0000 2026,en,1779978537776,0,3,0,0,39,False,MishraSheesh,SheeshC,53,False,False,Mumbai,42,284
37,2058414679899443220,Kapan lagi dapet HP yang all-in-one kayak Infi...,Sun May 24 05:07:57 +0000 2026,in,1779978537776,0,0,0,0,19,False,MiaJuanda7,Mia Juanda,16,False,False,,19,238
38,2058413807840714814,nyari hp mid-range yang paket lengkap buat gam...,Sun May 24 05:04:29 +0000 2026,in,1779978537776,0,0,0,0,11,False,Gilang9043,Gilang Bocah,288,False,False,,11,173
39,2058391958280716643,"I got a ton of computers, so i be tryna be nic...",Sun May 24 03:37:40 +0000 2026,en,1779978537776,0,0,0,0,16,False,Chief900Bill,Mr. Fore🍾🏌🏾‍♂️,1232,False,False,🍞In the Daßßy ♉️,16,206
40,2059892944702984655,I've been using these Galaxy Buds FE since Feb...,Thu May 28 07:02:03 +0000 2026,en,1779978537776,0,0,1,0,70,False,nagh_siva,ఏకం ఏవద్వితీయం,197,False,False,,71,308
41,2059875042381721992,"@XiaomiIndia I am using the Xiaomi 14 device, ...",Thu May 28 05:50:55 +0000 2026,en,1779978537776,0,1,0,0,11,False,VikashK35321493,Vikash Kaushik,84,False,False,"Palwal, India",12,278
42,2059869422777450814,New iPhone drop has me broke but hyped That c...,Thu May 28 05:28:35 +0000 2026,en,1779978537776,0,0,0,0,4,False,HK_Urban,Alex Urban,20,False,False,,4,83
43,2059837030629359975,Testing Android from an iPhone.\n\nThe game ru...,Thu May 28 03:19:52 +0000 2026,en,1779978537776,0,0,1,0,17,False,phonescloud99,phonescloud,11,False,True,HongKong,18,296
44,2059767572640280601,"With my experience as a phone vendor, this is ...",Wed May 27 22:43:52 +0000 2026,en,1779978537776,24,10,40,0,2233,False,Bigwavee00,Professor. EG ☎️🐐,70970,False,True,Where i want to be!,2307,516
45,2059730259835044211,Never buy a Samsung Galaxy A03 no matter how d...,Wed May 27 20:15:36 +0000 2026,en,1779978537776,0,1,7,0,128,False,D4rkwinger,Dark-winged Ducklett,456,False,False,NYC,136,173
46,2059716370187563072,IPhones are overrated. I had been trying to su...,Wed May 27 19:20:24 +0000 2026,en,1779978537776,0,0,0,0,23,False,Ajayi_tweets,Àjàyí—Olúwaṣeun🦅,6547,False,False,Lagos southwest,23,276
47,2059688011512913978,"How many Pixel phones have you used so far, an...",Wed May 27 17:27:43 +0000 2026,en,1779978537776,6,132,108,1,8299,False,pixeluibygoogle,Pixel UI by Google,10008,False,True,India,8546,145
48,2059627109015064990,pano nga magembed vid sa iphone??? i got no pr...,Wed May 27 13:25:43 +0000 2026,tl,1779978537776,0,1,0,0,36,False,joshubaeks,sette (⌐■֊■),384,False,False,🇵🇭 she/her '99,37,70
49,2059590519563718940,You forgot your camera but the Xiaomi 17T Pro ...,Wed May 27 11:00:19 +0000 2026,en,1779978537776,0,0,0,0,335,False,GamerBraves,GamerBraves,2010,False,False,,335,123
50,2059565167050989784,"I sell my iPhone last year, con Dey use androi...",Wed May 27 09:19:35 +0000 2026,en,1779978537776,0,0,2,0,24,False,CallmeRehoboth,REHOBOTH 🇬🇧🇳🇬🏖️,511,False,False,Outta this world,26,100
51,2059548720102797410,I remember when I bought my digital camera and...,Wed May 27 08:14:14 +0000 2026,en,1779978537776,53,36,1613,2,141005,False,queenbeth____,Beth♥️,19354,False,True,"Lagos, Nigeria",142709,414
52,2059472362417099099,"1.5 years ago, I bought these OnePlus Bluetoot...",Wed May 27 03:10:49 +0000 2026,en,1779978537776,14,21,53,11,5098,False,imDev02,Dev Ashish 2.0,13948,False,True,India,5197,851
53,2059419294560383391,yes i bought a new iphone just to have a bette...,Tue May 26 23:39:56 +0000 2026,en,1779978537776,0,0,0,0,29,False,moonsunmates,aly j ⁷ ✨,178,False,False,she/her ⋆ 31 ⋆ queer • libra,29,93
54,2059393522185163114,4 years ago today I got the 13 pro max brand n...,Tue May 26 21:57:32 +0000 2026,en,1779978537776,0,0,1,0,63,False,DylSki02,DylSkiii,24,False,False,"England, United Kingdom",64,202
55,2059345048131494353,Did yall know on iPhone your icons move as u m...,Tue May 26 18:44:54 +0000 2026,en,1779978537776,0,1,0,0,27,False,HOODIE_ROSS222,Hoodie Ross,339,False,True,Kingdom of God,28,289
56,2059330248416661901,"The vivo V70 FE 5G is here… and at R16,999, it...",Tue May 26 17:46:06 +0000 2026,en,1779978537776,0,0,0,0,36,False,TechSceneZA,Tech Scene ZA,174,False,False,durban,36,303
57,2059329134283657277,"Contrary to popular belief, the Tesla battery ...",Tue May 26 17:41:40 +0000 2026,en,1779978537776,0,1,3,0,76,False,U_cutz,Bobby Brar,676,False,True,"Brampton, Ontario",80,239
58,2059294605825462357,"Samsung lowkey the most worth it good camera,...",Tue May 26 15:24:28 +0000 2026,en,1779978537776,0,0,0,0,142,False,AstiaSeyen6838,Sey˚ʚ🍓ɞ˚♡,22,False,False,Indonesia,142,109
59,2059255061424087332,What are y’all battery health in your IPhones?...,Tue May 26 12:47:20 +0000 2026,en,1779978537776,0,1,1,0,51,False,Drixstarnothere,Drop/Rain,2059,False,False,He/Him || 19 🇵🇭,53,141