## Visualice the .parquet files saved in datalake_gold

Import libraries and declare paths

In [1]:
from pathlib import Path

GOLD_BASE_PATH = "../datalake_gold"

gold_files = sorted(Path(GOLD_BASE_PATH).rglob("*.parquet"))

for f in gold_files:
    print(f)

..\datalake_gold\brand_analytics_weekly_20260530_200341.parquet
..\datalake_gold\brand_analytics_weekly_20260530_200341.parquet\part-00000-43379565-9528-459f-b217-5c1b36f46f44-c000.snappy.parquet
..\datalake_gold\governance\news\governance_news_weekly_20260530_200322.parquet
..\datalake_gold\governance\news\governance_news_weekly_20260530_200322.parquet\part-00000-d7c4f23f-c4dc-4d3e-aafb-ec844028786c-c000.snappy.parquet
..\datalake_gold\governance\tweets\governance_tweets_weekly_20260530_200322.parquet
..\datalake_gold\governance\tweets\governance_tweets_weekly_20260530_200322.parquet\part-00000-82734d2b-071b-420a-85a7-8e0943577fef-c000.snappy.parquet
..\datalake_gold\product_analytics_weekly_20260530_200340.parquet
..\datalake_gold\product_analytics_weekly_20260530_200340.parquet\part-00000-2c169af2-4c76-4bc1-876a-b325c818dd00-c000.snappy.parquet
..\datalake_gold\representative_comments_weekly_20260530_200340.parquet
..\datalake_gold\representative_comments_weekly_20260530_200340.parquet\part-00000-87d5fa96-87ea-4b5a-a256-e84c3a95d8e7-c000.snappy.parquet
..\datalake_gold\storytelling_weekly_20260530_200353.parquet
..\datalake_gold\storytelling_weekly_20260530_200353.parquet\part-00000-8182a0b5-63f2-4150-a6eb-0560e01d6af4-c000.snappy.parquet
..\datalake_gold\top_influencers_weekly_20260530_200340.parquet
..\datalake_gold\top_influencers_weekly_20260530_200340.parquet\part-00000-3c7a06ff-537f-4cee-b58c-5005009f13f9-c000.snappy.parquet
..\datalake_gold\topic_analytics_weekly_20260530_200340.parquet
..\datalake_gold\topic_analytics_weekly_20260530_200340.parquet\part-00000-bbef263d-5cb6-4a45-91ae-bc005b5d85eb-c000.snappy.parquet

---

In [2]:
from pathlib import Path
import pandas as pd

GOLD_PATH = Path("../datalake_gold")

datasets = [
    p for p in GOLD_PATH.rglob("*.parquet")
    if p.is_dir()
]

print(f"Datasets encontrados: {len(datasets)}")

for dataset in datasets:
    print("\n" + "=" * 120)
    print(dataset.relative_to(GOLD_PATH))

    df = pd.read_parquet(dataset)

    print(f"Rows: {len(df)}")
    print(f"Columns: {len(df.columns)}")

    display(df.head())

Datasets encontrados: 16

========================================================================================================================
brand_analytics_weekly_20260530_200341.parquet
Rows: 23
Columns: 10

,week,brand,mentions_twitter,mentions_news,total_mentions,total_engagement,positive_pct,negative_pct,neutral_pct,avg_score
0,22,apple,18,19,37,3886,73.0,10.8,16.2,0.5179
1,22,samsung,4,15,19,9,68.4,21.1,10.5,0.5430
2,22,hp,5,0,5,53,100.0,0.0,0.0,0.2958
3,22,sony,1,4,5,0,40.0,20.0,40.0,0.2652
4,22,xiaomi,2,2,4,1,75.0,25.0,0.0,0.5705

========================================================================================================================
brand_analytics_weekly_20260602_214550.parquet
Rows: 15
Columns: 10

,week,brand,mentions_twitter,mentions_news,total_mentions,total_engagement,positive_pct,negative_pct,neutral_pct,avg_score
0,23,apple,60,28,88,690,75.0,11.4,13.6,0.4965
1,23,google,0,32,32,0,37.5,50.0,12.5,0.4648
2,23,xiaomi,2,30,32,0,68.8,12.5,18.8,0.4080
3,23,samsung,2,8,10,258,40.0,0.0,60.0,0.2570
4,23,nvidia,6,0,6,4,33.3,0.0,66.7,0.1953

========================================================================================================================
product_analytics_weekly_20260530_200340.parquet
Rows: 9
Columns: 8

,week,product,brand,mentions,positive_pct,negative_pct,neutral_pct,avg_score
0,22,iphone,apple,30,76.7,13.3,10.0,0.5404
1,22,headphones,NaN,7,57.1,28.6,14.3,0.5580
2,22,earbuds,sony,7,71.4,28.6,0.0,0.4553
3,22,galaxy,samsung,5,100.0,0.0,0.0,0.6704
4,22,macbook,apple,4,50.0,0.0,50.0,0.4111

========================================================================================================================
product_analytics_weekly_20260602_214552.parquet
Rows: 9
Columns: 8

,week,product,brand,mentions,positive_pct,negative_pct,neutral_pct,avg_score
0,23,iphone,apple,42,66.7,9.5,23.8,0.4395
1,23,macbook,apple,18,88.9,11.1,0.0,0.4833
2,23,headphones,bose,16,50.0,50.0,0.0,0.5162
3,23,galaxy,samsung,10,40.0,0.0,60.0,0.2570
4,23,earbuds,jbl,10,80.0,20.0,0.0,0.6172

========================================================================================================================
storytelling_weekly_20260530_200353.parquet
Rows: 1
Columns: 10

,week,brand,best_comment,worst_comment
0,22,bose,"1/ Really disappointed with Bose ending cloud support for the SoundTouch 20. I bought this as a premium connected speaker system, not just a basic Bluetooth speaker. Now Bose has effectively stripped away key functionality from a product customers paid hundreds for.",None
1,22,sony,"Ever forget you’re wearing earbuds until the battery dies? We tested the Sony LinkBuds Fit through workouts, errands, and long days. Worth it?","AnonD-140756, 29 Apr 2013why ddnt anyone mention the sony xperia z display in this article ? ^o)Because it is really crap!"
2,22,samsung,"I've been using these Galaxy Buds FE since February 2024, &amp; they seriously one of the best TWS for my Samsung smartphone. *Punchy, enriched bass &amp; surround sound (better than Galaxy Buds Pro) *Powerful ANC *Good battery life *The best ergonomic wingtip design *Timely updatess",Ppl writing stories here. Samsung accepted s4 s not best. Then y cry over here
3,22,garmin,None,When my Garmin watch falls off at night and has no data so it resets my body battery to 50. Ha! As if. It hasn't recharged to above 30 in the 3 and 1/2 years since I got it...
4,22,jbl,"Big buyer's remorse on the the choice of color (they had a nice variety, including fire engine red) I got for my new JBL portable bluetooth speaker to hang from my handlebars when I go biking. It looks like a Fleshlight® 🫤",None

========================================================================================================================
storytelling_weekly_20260530_200353.parquet
Rows: 1
Columns: 10

,week,executive_summary,top_brand,best_brand,worst_brand,brand_sentiment_snapshot,top_positive_topics,top_negative_topics,top_products,representative_comments
0,22,Apple fue la marca más mencionada durante la s...,apple,hp,msi,"[{""brand"": ""apple"", ""total_mentions"": 37, ""pos...","[""performance"", ""smartwatch"", ""battery""]","[""charging"", ""audio"", ""ai""]","[""iphone"", ""headphones"", ""earbuds"", ""galaxy"", ...","[{""brand"": ""bose"", ""best_comment"": ""1/ Really ..."

========================================================================================================================
top_influencers_weekly_20260530_200340.parquet
Rows: 20
Columns: 7

,brand,author_userName,followers,engagement,tweet_count,sentiment,week
0,apple,SnazzyLabs,295464,2095,1,positive,22
1,apple,queenbeth____,19354,1704,1,positive,22
2,fitbit,DurvidImel,76329,1363,1,positive,22
3,google,pixeluibygoogle,10008,247,1,positive,22
4,oneplus,imDev02,13948,99,1,positive,22

========================================================================================================================
topic_analytics_weekly_20260602_214552.parquet
Rows: 12
Columns: 7

,week,topic,mentions,positive_pct,negative_pct,neutral_pct,avg_score
0,23,software,118,54.2,27.1,18.6,0.4479
1,23,battery,34,88.2,11.8,0.0,0.6435
2,23,camera,26,53.8,23.1,23.1,0.5357
3,23,audio,22,54.5,18.2,27.3,0.3811
4,23,display,16,50.0,25.0,25.0,0.4062

========================================================================================================================
representative_comments_weekly_20260530_200340.parquet
Rows: 23
Columns: 4

,week,brand,best_comment,worst_comment
0,22,bose,1/ Really disappointed with Bose ending cloud ...,NaN
1,22,sony,Ever forget you’re wearing earbuds until the b...,"AnonD-140756, 29 Apr 2013why ddnt anyone menti..."
2,22,samsung,I've been using these Galaxy Buds FE since Feb...,Ppl writing stories here. Samsung accepted s4 ...
3,22,garmin,NaN,When my Garmin watch falls off at night and ha...
4,22,jbl,Big buyer's remorse on the the choice of color...,NaN

========================================================================================================================
top_influencers_weekly_20260602_214550.parquet
Rows: 20
Columns: 7

     brand author_userName  followers  engagement  tweet_count sentiment  week
0    apple      heyjames01        133         466            2  positive    23
1  samsung   openshutter21      32897         258            2  positive    23
2    apple    MehakdeepK81        220          54            2  positive    23
3    apple        xrihxrih        299          54            2  positive    23
4    apple    Emmy_Crrypto      32281          32            2  positive    23

========================================================================================================================
topic_analytics_weekly_20260530_200340.parquet
Rows: 13
Columns: 7

                                                                                             newsLink  \
0  https://www.gsmarena.com/xiaomi_unveils_smart_band_10_pro_buds_6_sound_play_speaker-news-73032.php
1  https://www.gsmarena.com/xiaomi_unveils_smart_band_10_pro_buds_6_sound_play_speaker-news-73032.php
2  https://www.gsmarena.com/xiaomi_unveils_smart_band_10_pro_buds_6_sound_play_speaker-news-73032.php
3  https://www.gsmarena.com/xiaomi_unveils_smart_band_10_pro_buds_6_sound_play_speaker-news-73032.php
4  https://www.gsmarena.com/xiaomi_unveils_smart_band_10_pro_buds_6_sound_play_speaker-news-73032.php

     date_day  week  \
0  2026-05-29    22
1  2026-05-29    22
2  2026-05-29    22
3  2026-05-29    22
4  2026-05-29    22

                                                                                                                                                                                                                             comment_text  \
0         I like how at least some still make earbuds without silicone tips. I really don't like those. \n \nAlso, is Xiaomi Watch S5 any good? I'm currently on old Galaxy Watch 4 and I'm slowly looking for alternatives or options...
1                                                      is it still qualified as a smart "band"? it's too big and heavy for a "band", just call it a smart "watch" at this point. not just xiaomi, huawei also made the exact same mistake
2  Hamad1993, 28 May 2026So this one or huwaei band 11?Wait for The Quantified Scientist YouTube channel to do his usual stress test regarding the Smart Band 10 Pro. He already did the Huawei Band 11, and the results are pretty good.
3                                    dexterouz, 28 May 2026For that, I'm waiting for "The Quantified Scientist" review to drop. And pretty... moreHopefully he also reviews the watch S5, really curious if they improved sleep tracking.
4                                                      Anonymous, 28 May 2026Earbuds without eartips aka open earbuds are no go if you really love load and bassy music.Some people don't support to have something so deep in their ears

     brand  product        topic sentiment  sentiment_score
0  samsung   galaxy  performance  positive           0.4609
1   xiaomi     None   smartwatch  positive           0.4588
2   huawei     None           ai  positive           0.7184
3     None     None           ai  positive           0.7778
4     None  earbuds         None  positive           0.2582

========================================================================================================================
governance/tweets/governance_tweets_weekly_20260530_200322.parquet
Rows: 60
Columns: 18

,tweet_id,date_day,week,author_userName,author_followers,text,lang,total_engagement,likeCount,replyCount,retweetCount,quoteCount,brand,product,topic,sentiment,sentiment_score,experience_type
0,2060004476669374743,2026-05-28,22,SouthernFreeez,315,1/ Really disappointed with Bose ending cloud ...,en,1,0,1,0,0,bose,NaN,software,positive,0.2975,personal_experience
1,2059950505447584179,2026-05-28,22,oluwafemi10591,4126,I got into a screaming match on the bus this m...,en,1,1,0,0,0,NaN,headphones,camera,negative,0.9787,personal_experience
2,2059950392176234910,2026-05-28,22,oluwafemi10591,4126,I got into a screaming match on the bus this m...,en,1,1,0,0,0,NaN,headphones,camera,negative,0.9787,personal_experience
3,2059937735977398654,2026-05-28,22,GearReview,4058,Ever forget you’re wearing earbuds until the b...,en,0,0,0,0,0,sony,earbuds,battery,positive,0.4329,personal_experience
4,2059914754030776460,2026-05-28,22,CDLHater,26352,Dashy talks about Mercules' camera falling on ...,en,395,391,0,4,0,NaN,earbuds,camera,negative,0.1406,personal_experience